FROM python:3.11.4-slim-buster

WORKDIR /app

COPY requirements-dev.txt requirements-dev.txt
COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements-dev.txt && \
    pip install --no-cache-dir -r requirements.txt

ENV PYTHONPATH=/app

ENTRYPOINT ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--no-browser", "--NotebookApp.token=''"]
