FROM python:3.11.4-slim-buster

WORKDIR /app

ENV PYTHONPATH=/app
ENV FLASK_APP=src/app.py

COPY requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt

COPY . .

EXPOSE 5000

ENTRYPOINT ["bash", "./entrypoint.sh"]
